# Generated by Django 4.2.6 on 2023-10-15 02:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AuthGroup",
        ),
        migrations.DeleteModel(
            name="AuthGroupPermissions",
        ),
        migrations.DeleteModel(
            name="AuthPermission",
        ),
        migrations.DeleteModel(
            name="AuthUser",
        ),
        migrations.DeleteModel(
            name="AuthUserGroups",
        ),
        migrations.DeleteModel(
            name="AuthUserUserPermissions",
        ),
        migrations.DeleteModel(
            name="DjangoAdminLog",
        ),
        migrations.DeleteModel(
            name="DjangoContentType",
        ),
        migrations.DeleteModel(
            name="DjangoMigrations",
        ),
        migrations.DeleteModel(
            name="DjangoSession",
        ),
        migrations.AlterModelOptions(
            name="artist",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="artwork",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="donor",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="images",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="location",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="moverequest",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="privs",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="requesttype",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="usertype",
            options={"managed": True},
        ),
    ]
