# Generated by Django 4.2.7 on 2023-11-16 18:42

import api.storage_backends.PublicMediaStorage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_category_options_migrationrequest_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artworkimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='artworkimage',
            name='image_file',
            field=models.FileField(default='uploads', storage=api.storage_backends.PublicMediaStorage.PublicMediaStorage(), upload_to='artworks'),
        ),
    ]
