# Generated by Django 4.2.5 on 2023-11-17 05:00

import api.storage_backends.PublicMediaStorage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_artworkimage_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='migrationrequest',
            name='user',
        ),
        migrations.AddField(
            model_name='migrationrequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='artworkimage',
            name='image_file',
            field=models.FileField(default='uploads', storage=api.storage_backends.PublicMediaStorage.PublicMediaStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='migrationrequest',
            name='current_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_location_requests', to='api.location'),
        ),
        migrations.AlterField(
            model_name='migrationrequest',
            name='new_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='new_location_requests', to='api.location'),
        ),
    ]
